name: Seonghun's Daily Routine
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Seonghun's Github Routine
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 9842e074b8ee46aef76fd0d493bae0ed
          TIMEZONE: Asia/Seoul
